config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  resources :sensor_stations
  resources :sensors
  resources :data_sources
  resources :unit_categories
  resources :units

  root 'data_sources#index'

  get 'unit_categories/:id/getMainUnit', to: 'unit_categories#get_main_unit', :as => :main_unit, :via => :get
  get 'unit_categories/:id/units', to: 'unit_categories#get_units', :as => :all_units, :via => :get

  get 'data_sources/:id/measurements', to: 'data_sources#get_measurements', :as => :all_measurements, :via => :get
  get 'data_sources/:id/getValidationSchema', to: 'data_sources#json_schema', :as => :validation_schema, :via => :get
  get 'measurements/:id/data_sources', to: 'measurements#get_data_sources', :as => :all_data_sources, :via => :get

end

app/models/data_source.rb
class DataSource < ActiveRecord::Base
	  has_and_belongs_to_many :sensor_stations
	  has_and_belongs_to_many :measurements
	  validates_presence_of :name
end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_action :set_data_source, only: [:show, :edit, :update, :destroy, :json_schema, :get_measurements]

  # GET /data_sources
  # GET /data_sources.json
  def get_measurements
    render json: @data_source.measurements
  end

  def index
    @data_sources = DataSource.all
  end

  # GET /data_sources/1
  # GET /data_sources/1.json
  def show
  end

  # GET /data_sources/new
  def new
    @data_source = DataSource.new
  end

  # GET /data_sources/1/edit
  def edit
  end

  # POST /data_sources
  # POST /data_sources.json
  def create
    @data_source = DataSource.new(data_source_params)

    respond_to do |format|
      if @data_source.save
        format.html { redirect_to @data_source, notice: 'Data source was successfully created.' }
        format.json { render :show, status: :created, location: @data_source }
      else
        format.html { render :new }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_sources/1
  # PATCH/PUT /data_sources/1.json
  def update
    respond_to do |format|
      if @data_source.update(data_source_params)
        format.html { redirect_to @data_source, notice: 'Data source was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_source }
      else
        format.html { render :edit }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sources/1
  # DELETE /data_sources/1.json
  def destroy
    @data_source.destroy
    respond_to do |format|
      format.html { redirect_to data_sources_url, notice: 'Data source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def json_schema
    schema = {
      "$schema": "http://json-schema.org/schema#",
      "title": "Data Source",
      "description": "A Data Source for Open Sensor Data from the CP project at TU Berlin. ",
      "type": "object",
      "properties": {
        "source_id": {"const": @data_source.slug},
        "device": {"type": "string"},
        "timestamp": { "type": "string", "format": "date-time" },
        "timestamp_data": { "type": "string", "format": "date-time" },
        "location": {
          "type": "object",
          "properties": {
            "lat": {"type": "number",
                    "exclusiveMaximum": true,
                    "exclusiveMinimum": true,
                    "maximum": 90,
                    "minimum": -90
                   },
            "lon": {"type": "number",
                    "exclusiveMaximum": true,
                    "exclusiveMinimum": true,
                    "maximum": 180,
                    "minimum": -180,
                   }
          },
        "required": ["lat", "lon"]
        },
        "license": {"type": "string"},
        "sensors": {
          "type": "object",
          "items": [
          {
            "type": "object",
            "properties": {
              "sensor": {"type": "string"},
              "observation_type": {"type": "string"},
              "observation_value": {"type": "number"}
            }
          }]
        }
      },
      "required": ["source_id", "timestamp","sensors", "location", "license"]
  }

  render json: schema
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_source
      @data_source = DataSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_source_params
      params.require(:data_source).permit(:stil_active, :source_root_url, :startdate, :name, :desc, :license, :docker_image_location, :schedule_cron, :slug, :enddate, :measurement_ids => [])
    end
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/data_sources/_form.html.erb
<%= simple_form_for(@data_source, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :startdate, :start_year => Date.today.year - 200, :end_year => Date.today.year %>
    <%= f.input :stil_active %>
    <%= f.input :enddate, :start_year => Date.today.year - 200, :end_year => Date.today.year, label: 'Enddate (if not active anymore)' %>
    <%= f.input :license %>
    <%= f.input :slug, label: "Slug (used as index for datasource)" %>
    <%= f.input :source_root_url %>
    <%= f.input :docker_image_location %>
    <%= f.input :schedule_cron %>
    <p>Please use a crontab like syntax for the schedule</p>
    <%= f.input :measurement_ids, collection: Measurement.all, input_html: { class: 'multipleSelect', multiple: true} %>
  <p>Measurement missung? <%= link_to 'Add Measurement', new_measurement_path, target: :_blank %></p>

  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>



<%= javascript_include_tag "jquery-multi-select" %>
<script type="text/javascript">
  $('.multipleSelect').multiSelect()
</script>

app/views/data_sources/edit.html.erb
<h1>Editing Data Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_source %> |
<%= link_to 'Back', data_sources_path %>

app/views/data_sources/index.html.erb
<h1>Listing Data Sources</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Startdate</th>
      <th>Stil active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_sources.each do |data_source| %>
      <tr>
        <td><%= data_source.name %></td>
        <td><%= data_source.desc %></td>
        <td><%= data_source.startdate %></td>
        <td><%= data_source.stil_active %></td>
        <td><%= link_to 'Show', data_source %></td>
        <td><%= link_to 'Edit', edit_data_source_path(data_source) %></td>
        <td><%= link_to 'Destroy', data_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data source', new_data_source_path %>

app/views/data_sources/new.html.erb
<h1>New Data Source</h1>

<%= render 'form' %>

<%= link_to 'Back', data_sources_path %>

app/views/data_sources/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @data_source.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @data_source.desc %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @data_source.startdate %>
</p>

<p>
  <strong>Stil active:</strong>
  <%= @data_source.stil_active %>
</p>

<p>
  <strong>Source root url:</strong>
  <%= @data_source.source_root_url %>
</p>

<p>
  <strong>License:</strong>
  <%= @data_source.license %>
</p>

<p><strong>Measurements:</strong><br>
<div style="padding-left: 2em;">
  
<% @data_source.measurements.each do |measurement| %>
  <%= link_to measurement.name, measurement %><br>
<% end %>
</div>
</p>


<%= link_to 'Edit', edit_data_source_path(@data_source) %> |
<%= link_to 'Back', data_sources_path %>