config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  resources :sensor_stations
  resources :sensors
  resources :data_sources
  resources :unit_categories
  resources :units

  root 'data_sources#index'

  get 'unit_categories/:id/getMainUnit', to: 'unit_categories#get_main_unit', :as => :main_unit, :via => :get
  get 'unit_categories/:id/units', to: 'unit_categories#get_units', :as => :all_units, :via => :get

  get 'data_sources/:id/measurements', to: 'data_sources#get_measurements', :as => :all_measurements, :via => :get
  get 'data_sources/:id/getValidationSchema', to: 'data_sources#json_schema', :as => :validation_schema, :via => :get
  get 'measurements/:id/data_sources', to: 'measurements#get_data_sources', :as => :all_data_sources, :via => :get

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
	belongs_to :unit
	belongs_to :unit_category
	has_and_belongs_to_many :data_sources
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy, :get_data_sources]

  def get_data_sources
    render json: @measurement.data_sources
  end

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        # @measurement.unit_category_id = measurement_params[:unit_category_id]
        # @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:name, :desc, :unit_category_id)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= simple_form_for(@measurement, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :unit_category_id, collection: UnitCategory.all %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing Measurement</h1>

<%= render 'form' %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Measurements</h1>

<table class="table sortable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Unit Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.name %></td>
        <td><%= measurement.desc %></td>
        <td><%= UnitCategory.find(measurement.unit_category_id).name %></td>
        <td><%= link_to 'Show', measurement %></td>
        <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
        <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measurement', new_measurement_path, class: 'btn btn-default' %>


<%= javascript_include_tag "sortable" %>

app/views/measurements/new.html.erb
<h1>New Measurement</h1>

<%= render 'form' %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @measurement.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @measurement.desc %>
</p>
<p>
  <strong>Unit Category:</strong>
  <%= link_to UnitCategory.find(@measurement.unit_category_id).name, UnitCategory.find(@measurement.unit_category_id) %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>