config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  resources :sensor_stations
  resources :sensors
  resources :data_sources
  resources :unit_categories
  resources :units

  root 'data_sources#index'

  get 'unit_categories/:id/getMainUnit', to: 'unit_categories#get_main_unit', :as => :main_unit, :via => :get
  get 'unit_categories/:id/units', to: 'unit_categories#get_units', :as => :all_units, :via => :get

  get 'data_sources/:id/measurements', to: 'data_sources#get_measurements', :as => :all_measurements, :via => :get
  get 'data_sources/:id/getValidationSchema', to: 'data_sources#json_schema', :as => :validation_schema, :via => :get
  get 'measurements/:id/data_sources', to: 'measurements#get_data_sources', :as => :all_data_sources, :via => :get

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebMgmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">CP Open Data Web mgmt</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
		<ul class="nav navbar-nav">
      <li><%= link_to '<i class="fa fa-list"></i> Data Sources'.html_safe, data_sources_path %></li>
			<li><%= link_to '<i class="fa fa-eye"></i> Measurements'.html_safe, measurements_path %></li>
      <li><%= link_to 'Units'.html_safe, units_path %></li>
      <li><%= link_to 'Unit Categories'.html_safe, unit_categories_path %></li>
      <li><%= link_to '<i class="fa fa-map-marker"></i> Sensor Stations'.html_safe, sensor_stations_path %></li>
      <li><%= link_to '<i class="fa fa-eye"></i> Sensors'.html_safe, sensors_path %></li>
		</ul>

    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= bootstrap_flash %>
    </div>
  </div>

	<div class="row">
		<div class="col-md-12">
			<%= yield %>
		</div>
	</div>
</div>


</body>
</html>